// <auto-generated />
using ItemManagment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItemManagment.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240709091606_AddDataToItems")]
    partial class AddDataToItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("ItemManagment.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Internal_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Serial_number")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lenovo H/Y i5",
                            Internal_code = "E/B/0000",
                            Serial_number = "AASSDD8875"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lenovo H/Y i5",
                            Internal_code = "E/B/0000",
                            Serial_number = "AASSDD8975"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lenovo Screen 24\"",
                            Internal_code = "E/B/1111",
                            Serial_number = "AASSDD2222"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xiaomi RedMi Note 8",
                            Internal_code = "E/B/1110",
                            Serial_number = "AASSDD0000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
